### ISSUE TITLE
订阅任务的时候遇到问题

### ISSUE THREAD

**Issue by Tao-bug** [Loon0x00/Bugs-Feedback#13]
我在自己仓库写好了Task，但是Loon订阅的时候，提示没有任何脚本

https://raw.githubusercontent.com/tao-bug/Loon/master/Task.conf

但是里面明明有内容的呀，难道是格式不对吗，我只是把nzw9314大佬的内容删了一些而已呀

**Comment by yeahwangy** [comment]
`"` 和 `“` 的问题
`”0 0 8 * * *“` 改成 `"0 0 8 * * *"`

**Comment by Tao-bug** [comment]
> `"` 和 `“` 的问题
> `”0 0 8 * * *“` 改成 `"0 0 8 * * *"`

好奇怪的，我在working copy里面看着挺正常的，复制出来也能用，而且我也是直接复制粘贴的task，只是都是在copy里面进行的，结果这个引号还出现了问题，让大家见笑了
