### ISSUE TITLE
涉及局域网请求的脚本不能正常执行，且无请求记录

### ISSUE THREAD

**Issue by iepngs** [Loon0x00/Bugs-Feedback#33]
1. 在请求记录中没有局域网的请求，比如`http://192.168.32.151:8080/checkin`
2. 没有办法触发涉及相关局域网地址的脚本，类似：`http-request ^http:\/\/192\.168\.32\.151:8080 script-path=https://raw.githubusercontent.com/.../debug.js(仅做举例，地址不完整，不是地址的问题)`

> （经测试好像请求公网ip是有记录的？局域网的屏蔽被拦截了？）

> 希望能够解决，方便通过远程订阅的方式调试脚本，毕竟手机上写脚本还是比较累。

**Comment by Loon0x00** [comment]
需要在配置文件中的skip-proxy中除去192.168.0.0/16
