### ISSUE TITLE
request-body无法修改

### ISSUE THREAD

**Issue by iepngs** [Loon0x00/Bugs-Feedback#34]
传递修改后的request-body不能正常完成请求；
不能同时修改request-header和request-body；

以下为测试结果：
【运行结果：√】 `$done({header}) `，仅修改header
【运行结果：×】 `$done({body})`， 仅修改body
【运行结果：×】 `$done({headers, body})`，同时修改header和body
【运行结果：×】 `$done({header: headers, body: body})`，同时修改header和body
【运行结果：×】 `$done({headers: headers, body: body})`，同时修改header和body

(使用键值对传递参数时，建议header的键用headers，与$request-headers统一)

**Comment by Loon0x00** [comment]
能发一下测试环境配置和测试脚本么

iepngs <notifications@github.com> 于2020年5月27日周三 下午6:22写道：

**Comment by iepngs** [comment]
撸了个分支,正常的话应该可以跑起来：
[https://github.com/iepngs/Script](https://github.com/iepngs/Script)

**Comment by iepngs** [comment]
$done({})
$done({})
$done({})
$done({})
$done({})
$done({})
