### ISSUE TITLE
关于no-resolve参数和策略优先级的问题

### ISSUE THREAD

**Issue by psikent** [Loon0x00/Bugs-Feedback#38]
1.请问no-resolve参数官方支持吗？看非官方的用户手册里面的说明是支持的，实际使用并未生效。
2.关于策略优先级，请问单条策略和订阅策略的优先级孰高孰低？按照我的理解，单条策略一般是使用者个人对于订阅策略的补充，优先级应该高于订阅策略，但是用起来发现并不是这样。对于这个问题也没有发现权威的官方manual。

**Comment by Loon0x00** [comment]
1、no-resolve是比较旧版本的参数，新版中已经将其去掉，只要是使用代理的请求，域名解析都放到代理服务其中去解析
2、单个本地策略优先级是高于订阅的，如果发现不是这样可以提供一下复现场景，我验证一下是否是bug

Jason Liu <notifications@github.com>于2020年11月18日 周三09:34写道：

**Comment by psikent** [comment]
1.我理解的no-resolve是ip-cidr规则的参数，效果是只匹配ip请求，如请求是域名就直接跳过。如果不加no-resolve参数是先用定义的dns服务器进行域名解析，再匹配ip请求。如果不支持这个参数，针对某些排的比较前的ip-cidr规则，每次碰见都会强制进行域名解析，对系统开销较大。这是我个人的见解，如理解错误请见谅。
2.我个人加了一个域名后缀为cn走direct，但是不会生效。不知道有没有其他需要注意的地方

**Comment by Loon0x00** [comment]
1、抱歉，我把no-resolve当成force-remote理解了，目前no-resolve确实有点bug，感谢你的反馈，我们会尽快修复
2、rule优先级问题待我测试是否有无bug后给你反馈

Jason Liu <notifications@github.com> 于2020年11月18日周三 上午11:02写道：

**Comment by psikent** [comment]
哈哈，好的，谢谢

**Comment by Loon0x00** [comment]
no-resolve 已在2.1.10(274)中修复
