### ISSUE TITLE
关于V2ray中VMessAEAD的支持

### ISSUE THREAD

**Issue by 120318** [Loon0x00/Bugs-Feedback#40]
对于VMessAEAD
```在 v4.28.1 版本后，客户端 AlterID 设置为 0 代表启用 VMessAEAD ；服务端为自动适配，可同时兼容启用和未开启 VMessAEAD 的客户端。```

而使用loon的v2ray client配置，V2ray的server端频繁出现如下日志：
```
[Warning] github.com/v2fly/v2ray-core/v4/proxy/vmess/encoding: Critical Warning: potentially invalid user: a non VMessAEAD connection is received. From 2022 Jan 1st, this kind of connection will be rejected by default. You should update or replace your client software now.
```
Loon客户端没有办法填写alterId，猜测是alterId默认为0导致?

**Comment by Loon0x00** [comment]
能将一个节点借我测试一下么，我看看具体什么问题

dearjoey ***@***.***> 于2021年3月26日周五 下午8:42写道：

**Comment by Loon0x00** [comment]
修改默认加密方式为chacha20-ietf-poly1305即可
